### ISSUE TITLE
[Request] Add raw JSON support

### ISSUE THREAD

**Issue by MrBallade** [MrRazamataz/ChatMOTD#1]
Please add support for raw JSON formatted MOTDs.
This would allow the message to contain clickable links to commands and urls which is need to nicely link to an external Discord server, Dynmap url, or simply toggle a command using chat.

This can be achieved using the native `tellraw` command, but is cumbersome to make into a motd for when a player joins.

Other plugins which have this feature are not as simple in their purpose and add a lot of bloat to the experience.
With JSON support, this plugin will be the absolute ideal plugin for making a simple chat motd.

**Comment by MrRazamataz** [comment]
This has been added to the Spigot version of the plugin in #[e53de95](https://github.com/MrRazamataz/ChatMOTD/commit/e53de959a2176eacd382f3891524ecb0713b2bb1). It will not be added to the Nukkit version because bedrock edition doesn't support the more fancy tellraw things.  

The update is now [live on SpigotMC](https://www.spigotmc.org/resources/chatmotd.100844/update?update=532543) and is used like this:

* Create a file called `chatmotd.json` in the ChatMOTD plugin directory.
* Paste the exact JSON for your tell raw command, eg, the bit after the selector in the vanilla tellraw command.
* If the `chatmotd.json` file is present, it will override the motd in `chatmotd.txt`. You also can't use `/setchatmotd` when the plugin is using `chatmotd.json` as Minecraft chat doesn't support enough characters to paste all the JSON in correctly. You must just edit the file directly.
